version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json"}}
            - app-
      - run:
          name: Install depenencies
          command: npm install
       - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json"}}

  deploy-to-aws-s3:
      docker:
        - image: circleci/node:13.12.0
      working_directory: ~/repo
      steps:
        - checkout
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
        - run:  
            name: Installing AWS CLI
            working_directory: /
            command: | 
              sudo apt-get -y -qq update
              sudo apt-get install -y awscli
              sudo apt-get install -y python-pip python-dev build-essential
        - run:
            name: Build Project
            command: |
              npm install
              npm run build
              cd build 
              zip ../build.zip -r * .[^.]*
              echo "Build successful"
        - run:
            name: Deploy to AWS S3
            command: aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_DEV} --delete
              
  deploy-to-aws-cloudfront:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:  
          name: Installing AWS CLI
          working_directory: /
          command: | 
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build 
            zip ../build.zip -r * .[^.]*
            echo "Build successful"
      - run:
          name: Deploy to AWS Cloudfront
          command: |
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --paths /\*
                 
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows

workflows: 
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          requires: 
            - build
          filters:
            branches: 
              only:
                - develop
      - deploy-to-aws-cloudfront:
          requires: 
            - deploy-to-aws-s3
          filters:
            branches: 
              only:
                - develop


